Repository atlp-rwanda/e-commerce-ninjas-fe, pull requests merged in 2024-07, with the labels that each got.

#9 [#187862829] ft-create-landing-page
  .gitignore
  package-lock.json
  package.json
  public/assets/left-bottom.png
  public/assets/left-top.png
  public/assets/middle.png
  public/assets/right-bottom.png
  public/assets/right-top.png
  public/assets/shoe1.jpeg
  public/assets/shoe2.jpeg
  public/assets/shoe3.jpeg
  public/assets/shoe4.jpeg
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Sample.tsx
  src/components/product/Product.tsx
  src/pages/LandingPage.tsx
  src/store/features/product/productService.tsx
  src/store/features/product/productSlice.tsx
  src/store/store.ts
  src/styles/Colors.scss
  src/styles/Header.scss
  src/styles/LandingPage.scss
  src/styles/Product.scss
  src/styles/Sample.scss
  src/styles/index.scss
  src/utils/types/store.d.ts
Labels: ready-for-peer-review

#21 Login and create account with google
  README.md
  src/App.scss
  src/assets/styles/AdminHeader.scss
  src/assets/styles/Button.scss
  src/assets/styles/Categories.scss
  src/assets/styles/Colors.scss
  src/assets/styles/Footer.scss
  src/assets/styles/Header.scss
  src/assets/styles/Input.scss
  src/assets/styles/LandingPage.scss
  src/assets/styles/Loader.scss
  src/assets/styles/Product.scss
  src/assets/styles/Sample.scss
  src/assets/styles/SearchInput.scss
  src/assets/styles/SellerHeader.scss
  src/assets/styles/Sidebar.scss
  src/assets/styles/email.scss
  src/assets/styles/signup.scss
  src/assets/styles/style.scss
  src/components/GoogleCallback.tsx
  src/components/inputs/SearchInput.tsx
  src/pages/SignUp.tsx
  src/router.tsx
  src/store/features/auth/authService.tsx
  src/store/features/auth/authSlice.tsx
  src/test/Button.test.tsx
  src/utils/axios/axiosInstance.ts
  src/utils/types/store.d.ts
Labels: ready-for-peer-review

#12 Users should be presented with a reset password link
  .eslintrc.json
  netlify.toml
  package-lock.json
  package.json
  public/assets/images/resetPassword.png
  src/App.scss
  src/assets/styles/AdminHeader.scss
  src/assets/styles/Button.scss
  src/assets/styles/Categories.scss
  src/assets/styles/Footer.scss
  src/assets/styles/Header.scss
  src/assets/styles/Input.scss
  src/assets/styles/LandingPage.scss
  src/assets/styles/Product.scss
  src/assets/styles/Sample.scss
  src/assets/styles/SearchInput.scss
  src/assets/styles/SellerHeader.scss
  src/assets/styles/Sidebar.scss
  src/assets/styles/email.scss
  src/assets/styles/reset-password.scss
  src/assets/styles/signup.scss
  src/assets/styles/style.scss
  src/components/buttons/Button.tsx
  src/components/inputs/SearchInput.tsx
  src/components/layout/Header.tsx
  src/index.tsx
  src/pages/LandingPage.tsx
  src/pages/ResetPassword.tsx
  src/pages/SendResetPasswordLink.tsx
  src/router.tsx
  src/store/features/auth/authService.tsx
  src/store/features/auth/authSlice.tsx
  src/store/features/welcomeSlice.tsx
  src/store/store.ts
  src/stories/Button.stories.ts
  src/utils/axios/axiosInstance.ts
  src/utils/types/store.d.ts
  webpack.dev.config.ts
  webpack.prod.config.ts
Labels: Ready

#11 [starts #187900329] Start User-view-single-product
  .eslintrc.json
  build/index.html
  build/main.c05cff687073893a108e.js
  build/main.c05cff687073893a108e.js.LICENSE.txt
  package-lock.json
  package.json
  public/assets/0.png
  public/assets/1.png
  public/assets/2.png
  public/assets/3.png
  public/assets/4.png
  public/assets/5.png
  public/assets/images/user.png
  src/App.scss
  src/User.tsx
  src/assets/styles/SingleProduct.scss
  src/components/product/Product.tsx
  src/components/product/SingleProduct.tsx
  src/pages/LandingPage.tsx
  src/pages/ViewProduct.tsx
  src/router.tsx
  src/store/features/product/productService.tsx
  src/store/features/product/productSlice.tsx
  src/store/features/product/singleProductSlice.tsx
  src/store/store.ts
  src/utils/text/truncateString.ts
  src/utils/types/custom.d.ts
  src/utils/types/product.d.ts
  src/utils/types/store.d.ts
  tsconfig.json
Labels: ready-to-be-merged

#25 Ft password expiry checks 187584870
  package-lock.json
  package.json
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/hooks/useSocket.ts
  src/pages/LandingPage.tsx
  src/store/features/auth/authSlice.tsx
  src/store/features/notifications/notificationService.tsx
  src/store/features/notifications/notificationSlice.tsx
  src/store/features/welcomeSlice.tsx
  src/store/store.ts
  src/test/Button.test.tsx
  src/utils/socket/socket.ts
Labels: ready-for-peer-review

#23 [Delivers #187584867] User login with email and password
  bash.exe.stackdump
  public/assets/images/adminLogin.png
  public/assets/images/loginPhoto.png
  public/assets/images/sellerLogin.png
  public/assets/person.jpg
  public/index.html
  src/App.scss
  src/assets/styles/Footer.scss
  src/assets/styles/Header.scss
  src/assets/styles/LandingPage.scss
  src/assets/styles/Login.scss
  src/assets/styles/Queries.scss
  src/assets/styles/signup.scss
  src/assets/styles/style.scss
  src/components/buttons/Button.tsx
  src/components/inputs/Input.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/pages/AdminLogin.tsx
  src/pages/LandingPage.tsx
  src/pages/Login.tsx
  src/pages/SellerLogin.tsx
  src/pages/SendResetPasswordLink.tsx
  src/pages/SignUp.tsx
  src/pages/UserLogin.tsx
  src/router.tsx
  src/store/features/auth/authService.tsx
  src/store/features/auth/authSlice.tsx
  src/store/store.ts
  src/utils/types/store.d.ts
  tsconfig.json
Labels: ready-to-be-merged

#18 ft-notification-panel
  src/App.scss
  src/assets/styles/Header.scss
  src/assets/styles/LandingPage.scss
  src/assets/styles/Notifications.scss
  src/assets/styles/Product.scss
  src/assets/styles/Sample.scss
  src/assets/styles/style.scss
  src/components/layout/Header.tsx
  src/components/layout/notification.tsx
  src/store/features/notifications/notificationSlice.tsx
  src/store/store.ts
  src/utils/types/store.d.ts
Labels: ready-to-be-merged

#13 Users should be able to search
  public/assets/images/noResult.png
  src/App.scss
  src/assets/styles/CustomSelect.scss
  src/assets/styles/Search.scss
  src/assets/styles/SearchInput.scss
  src/components/Dropdown/CustomSelect.tsx
  src/components/buttons/Button2.tsx
  src/components/inputs/Input.tsx
  src/components/inputs/SearchInput.tsx
  src/pages/Search.tsx
  src/router.tsx
  src/store/features/product/productService.tsx
  src/store/features/product/productSlice.tsx
  src/store/store.ts
  src/utils/types/product.d.ts
  src/utils/types/store.d.ts
Labels: ready-to-be-merged

#28 Highlight product-menu on view-single-product
  src/User.tsx
  src/assets/styles/ImageSlider.scss
  src/components/images/ImageSlider.tsx
  src/components/layout/Header.tsx
Labels: fix

#34 ft-mark-all-notification-as-read
  .circleci/config.yml
  package-lock.json
  package.json
  src/assets/styles/Header.scss
  src/assets/styles/Notifications.scss
  src/components/layout/Header.tsx
  src/components/layout/notification.tsx
  src/store/features/notifications/notificationService.tsx
  src/store/features/notifications/notificationSlice.tsx
Labels: ready-for-peer-review

#35 Seller view collection products & view single product
  package-lock.json
  package.json
  src/App.scss
  src/assets/styles/Colors.scss
  src/assets/styles/SellerCollection.scss
  src/assets/styles/SellerHeader.scss
  src/assets/styles/SellerLayout.scss
  src/assets/styles/SellerProduct.scss
  src/assets/styles/tables.scss
  src/components/layout/SellerHeader.tsx
  src/components/layout/SellerLayout.tsx
  src/components/product/SellerProduct.tsx
  src/components/product/SingleProduct.tsx
  src/components/svg/AddImageSVG.tsx
  src/components/table/Table.tsx
  src/hooks/useSellerAuthCheck.ts
  src/pages/SellerLogin.tsx
  src/pages/seller/SellerCollection.tsx
  src/pages/seller/SellerDashboard.tsx
  src/pages/seller/SellerViewProduct.tsx
  src/router.tsx
  src/store/features/auth/authSlice.tsx
  src/store/features/product/productService.tsx
  src/store/features/product/sellerCollectionProductsSlice.tsx
  src/store/features/product/sellerProductSlice.tsx
  src/store/store.ts
  src/utils/types/product.d.ts
  src/utils/types/store.d.ts
  tsconfig.json
Labels: ready-for-peer-review

#46 Fx reset-password feature
  package-lock.json
  src/assets/styles/reset-password.scss
  src/components/GoogleCallback.tsx
  src/pages/ResetPassword.tsx
  src/utils/axios/axiosInstance.ts
Labels: ready-for-peer-review, fixed

#32 User create and View Cart
  .circleci/config.yml
  .vscode/settings.json
  build/index.html
  package-lock.json
  src/App.scss
  src/assets/styles/Colors.scss
  src/assets/styles/Header.scss
  src/assets/styles/Product.scss
  src/assets/styles/Sample.scss
  src/assets/styles/ViewCart.scss
  src/components/layout/Header.tsx
  src/components/layout/Sample.tsx
  src/components/product/Product.tsx
  src/components/product/SingleProduct.tsx
  src/pages/LandingPage.tsx
  src/pages/UserLogin.tsx
  src/pages/UserViewCart.tsx
  src/router.tsx
  src/store/features/carts/cartService.tsx
  src/store/features/carts/cartSlice.tsx
  src/store/store.ts
  src/utils/types/store.d.ts
  webpack.dev.config.ts
Labels: ready-for-peer-review

#43 ft-user-logout
  src/assets/styles/Header.scss
  src/assets/styles/Login.scss
  src/assets/styles/Notifications.scss
  src/assets/styles/Sample.scss
  src/components/GoogleCallback.tsx
  src/components/layout/Header.tsx
  src/components/layout/Logout.tsx
  src/components/layout/Sample.tsx
  src/components/layout/notification.tsx
  src/pages/SignUp.tsx
  src/pages/UserLogin.tsx
  src/router.tsx
  src/store/features/auth/authService.tsx
  src/store/features/auth/authSlice.tsx
Labels: ready-for-peer-review

#39 Admin should be able to assign roles [custome, merchant, admin]
  .gitignore
  .vscode/settings.json
  build/index.html
  build/main.c05cff687073893a108e.js
  build/main.c05cff687073893a108e.js.LICENSE.txt
  package-lock.json
  package.json
  src/App.scss
  src/assets/styles/AdminHeader.scss
  src/assets/styles/Header.scss
  src/assets/styles/Login.scss
  src/assets/styles/ViewCart.scss
  src/assets/styles/adminDashboard.scss
  src/assets/styles/email.scss
  src/assets/styles/signup.scss
  src/assets/styles/tables.scss
  src/assets/styles/users.scss
  src/components/GoogleCallback.tsx
  src/components/ResendEmail.tsx
  src/components/layout/AdminHeader.tsx
  src/components/layout/Header.tsx
  src/components/table/Table.tsx
  src/pages/AdminLogin.tsx
  src/pages/SignUp.tsx
  src/pages/admin/Dashboard.tsx
  src/pages/admin/Login.tsx
  src/pages/admin/OverView.tsx
  src/pages/admin/Users.tsx
  src/router.tsx
  src/store/actions/resetAction.ts
  src/store/features/admin/adminService.tsx
  src/store/features/admin/adminSlice.tsx
  src/store/features/auth/authService.tsx
  src/store/features/auth/authSlice.tsx
  src/store/features/product/sellerCollectionProductsSlice.tsx
  src/store/reducers/index.ts
  src/store/store.ts
  src/utils/protectRoute/ProtectedRoute.tsx
  src/utils/types/store.d.ts
  tsconfig.json
Labels: Ready, ready-to-be-merged

#38 Add products to wishlist
  package-lock.json
  src/components/product/Product.tsx
  src/components/product/SingleProduct.tsx
  src/pages/UserLogin.tsx
  src/store/features/wishlist/wishlistService.tsx
  src/store/features/wishlist/wishlistSlice.tsx
  src/store/reducers/index.ts
Labels: ready-for-peer-review

#50 A buyer should be able to checkout
  src/assets/styles/ViewCart.scss
  src/pages/ResetPassword.tsx
  src/pages/SendResetPasswordLink.tsx
  src/pages/UserViewCart.tsx
  src/store/features/carts/cartService.tsx
  src/store/features/carts/cartSlice.tsx
Labels: ready-for-peer-review
