Repository atlp-rwanda/e-commerce-ninjas-fe, pull requests merged in 2024-08, with the labels that each got.

#47 fixing Maxprice in user search
  .vscode/settings.json
  src/components/Dropdown/CustomSelect.tsx
  src/pages/Search.tsx
Labels: ready-for-peer-review

#55 ft Notifications
  src/assets/styles/AdminHeader.scss
  src/assets/styles/SellerHeader.scss
  src/components/layout/AdminHeader.tsx
  src/components/layout/Header.tsx
  src/components/layout/Logout.tsx
  src/components/layout/SellerHeader.tsx
  src/components/layout/SellerLayout.tsx
  src/components/layout/notification.tsx
  src/hooks/useSellerAuthCheck.ts
  src/hooks/useSocket.ts
  src/pages/LandingPage.tsx
  src/pages/SellerLogin.tsx
  src/pages/UserLogin.tsx
  src/pages/admin/Login.tsx
  src/store/features/notifications/notificationSlice.tsx
  src/utils/socket/socket.ts
Labels: ready-for-peer-review

#45 Ft user edit profile 187584875
  package-lock.json
  package.json
  public/assets/Camera.png
  public/assets/ProfileImage.jpg
  public/assets/Rwanda_.png
  public/assets/avatar.jpg
  public/assets/sellerI.png
  src/App.scss
  src/User.tsx
  src/assets/styles/SellerProduct.scss
  src/assets/styles/UserProfile.scss
  src/assets/styles/style.scss
  src/components/layout/Footer.tsx
  src/components/locations/location.ts
  src/components/product/Product.tsx
  src/components/product/SingleProduct.tsx
  src/components/user/PasswordUpdate.tsx
  src/components/user/ProfileDetails.tsx
  src/components/user/ShippingAddress.tsx
  src/components/user/SubmitSellerRequest.tsx
  src/pages/UserEditProfile.tsx
  src/router.tsx
  src/store/features/auth/authSlice.tsx
  src/store/features/product/singleProductSlice.tsx
  src/store/features/user/userService.tsx
  src/store/features/user/userSlice.tsx
  src/store/reducers/index.ts
  src/store/store.ts
  src/utils/axios/axiosInstance.ts
  src/utils/types/store.d.ts
  webpack.dev.config.ts
Labels: ready-for-peer-review

#54 Seller add/update product
  src/assets/styles/ImageSlider.scss
  src/assets/styles/SellerCollection.scss
  src/assets/styles/SellerLayout.scss
  src/assets/styles/SellerProduct.scss
  src/components/layout/SellerLayout.tsx
  src/components/product/SellerProduct.tsx
  src/components/table/Table.tsx
  src/pages/seller/SellerCollection.tsx
  src/store/features/product/productService.tsx
  src/store/features/product/sellerProductSlice.tsx
  src/utils/types/product.d.ts
  src/utils/types/store.d.ts
Labels: ready-for-peer-review

#62 Fix images counting bug
  src/components/product/SellerProduct.tsx
Labels: fix

#57 [Deliver -187584887 & 187584886] A buyer should update delete carts
  .vscode/settings.json
  src/assets/styles/ViewCart.scss
  src/pages/Products.tsx
  src/pages/UserViewCart.tsx
  src/router.tsx
  src/store/features/carts/cartService.tsx
  src/store/features/carts/cartSlice.tsx
Labels: ready-for-peer-review

#56 Users should be able to chat
  package-lock.json
  package.json
  public/assets/notification.mp3
  src/App.scss
  src/assets/styles/LandingPage.scss
  src/assets/styles/Product.scss
  src/assets/styles/ViewCart.scss
  src/assets/styles/liveChat.scss
  src/assets/styles/style.scss
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/live-chat/LiveChat.tsx
  src/components/product/Product.tsx
  src/index.tsx
  src/pages/Products.tsx
  src/pages/Search.tsx
  src/pages/UserViewCart.tsx
  src/pages/admin/Dashboard.tsx
  src/pages/admin/Users.tsx
  src/pages/seller/SellerDashboard.tsx
  src/store/actions/resetAction.ts
  src/store/features/auth/authSlice.tsx
  src/store/features/carts/cartSlice.tsx
  src/store/features/chat/chatSlice.tsx
  src/store/reducers/index.ts
  src/utils/protectRoute/ProtectedRoute.tsx
  src/utils/types/custom.d.ts
  src/utils/types/store.d.ts
  webpack.dev.config.ts
  webpack.prod.config.ts
Labels: ready-to-be-merged

#58 ft Admin and Seller Static Graphs Dashboard
  package-lock.json
  package.json
  public/assets/images/greenLines.png
  public/assets/images/redLines.png
  src/App.scss
  src/assets/styles/SellerLayout.scss
  src/assets/styles/adminDashboard.scss
  src/assets/styles/cards.scss
  src/components/cards/cards.tsx
  src/components/layout/SellerLayout.tsx
  src/pages/admin/Dashboard.tsx
  src/pages/admin/OverView.tsx
  src/pages/seller/SellerDashboard.tsx
  src/store/features/admin/adminService.tsx
  src/store/features/admin/adminSlice.tsx
  src/store/features/product/productService.tsx
  src/store/features/product/sellerCollectionProductsSlice.tsx
Labels: ready-for-peer-review

#77 Ft seller export stats
  package-lock.json
  package.json
  src/assets/styles/SellerLayout.scss
  src/pages/seller/SellerDashboard.tsx
  src/utils/excel/exportToCSV.ts
  src/utils/excel/exportToExcel.ts
Labels: ready-to-be-merged
